#!/usr/bin/env python3
"""Composition-surface write primitive — single source of truth for marker-fenced file composition.

Exposes Pattern C primitives: extract_operator_additions (pure read) and
write_managed_file (pure write). These replace the duplicated Python heredocs
previously embedded in update.sh and docs/scripts/setup-workspace.sh.

Spec: core/standards/composition-surface-spec.md §2-§3 (marker syntax, regeneration semantics).
Token vocabulary: core/standards/depersonalization-spec.md §1.

Two-hash separation (ADR-014): the MANAGED fence carries two SHA markers.
`managed_sha` is the SHA of the source template (pre-substitution) — the
regeneration trigger. `installed_sha` is the SHA of the post-substitution
installed managed body (the exact bytes this writer emits as the body) — the
tamper-detection anchor. They differ by design for token-bearing files (the
installed body is token-substituted), so tamper detection MUST compare against
`installed_sha`, never `managed_sha`. `_extract_managed_body` defines the
canonical body byte-domain shared by the writer (`write_managed_file`) and the
reader (the `installed-sha` subcommand), so the two cannot drift.

Public API (Python):
    extract_operator_additions(target_path) -> str
    write_managed_file(source_path, target_path, tokens, preserved_additions,
                       source_sha, tokens_flag) -> None
    regen_one_file(source_path, target_path, operator_toml_path,
                   override_toml_path, tokens_flag, source_sha) -> None
    installed_sha_of(target_path) -> str   # tamper anchor of an installed file ("" if no fence/body)
    resolve_repo_root_with_source(cli_value, *, install_state, declared_source,
                                  source_tree) -> RootResolution(root, source, notes)
    resolve_repo_root(cli_value, **tiers) -> str
    RepoRootUnresolvable                   # no tier yields a valid [PMO_PLATFORM_ROOT]

CLI:
    extract       --target <path>
    write         --source <path> --target <path> --operator-toml <path>
                  [--override-toml <path>] --tokens-flag {tokens,raw}
                  --source-sha <sha> [--preserved-additions-file <path>]
                  [--dialect {plain,markdown}] [--repo-root <path>]
    regen         --source <path> --target <path> --operator-toml <path>
                  [--override-toml <path>] --tokens-flag {tokens,raw} --source-sha <sha>
                  [--dialect {plain,markdown}] [--repo-root <path>]
    installed-sha --target <path>          # hex digest of the installed managed body ("" if none)
    resolve-root  [--repo-root <path>] [--install-state <file> | --declare-source <dir>]
                  [--source-tree <dir>]    # "<root>\t<tier>" on stdout; exit 3 if unresolvable

A write or regen whose template carries [PMO_PLATFORM_ROOT] resolves it once; a
template without the token never consults the resolver. When no tier yields a valid
root the command fails with exit 3 and writes nothing: the token never survives
unsubstituted into a deployed file.

Marker dialects (ADR-122): the writer emits the fence in the dialect the target's
manifest row declares — `plain` (comment-prefixed) or `markdown` (HTML-comment).
`plain` is the default, so a caller that passes no dialect gets byte-identical
output to the pre-ADR-122 writer. Both readers are dialect-AGNOSTIC by design.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, NamedTuple, Optional, Tuple

BEGIN_MANAGED = "# === BEGIN MANAGED SECTION (regenerated by update.sh; do not edit) ==="
END_MANAGED = "# === END MANAGED SECTION ==="
BEGIN_OPERATOR = "# === BEGIN OPERATOR ADDITIONS (preserved across updates) ==="
END_OPERATOR = "# === END OPERATOR ADDITIONS ==="

DEFAULT_OPERATOR_ADDITIONS_PLACEHOLDER = (
    "# Add custom entries below. update.sh never touches this section."
)

# --- Marker dialects (ADR-122) ---------------------------------------------
# A composition-surface target's fence is emitted in the dialect its manifest
# row declares. `plain` is the comment-prefixed form used by every allowlist,
# mode file, and .toml/.txt surface; `markdown` is the HTML-comment form the
# spec defines for markdown surfaces (§2.2). `plain` is the DEFAULT: a manifest
# row that omits the dialect field resolves to it, so every pre-ADR-122 row is
# unchanged and un-rewritten.
#
# The dialect is a WRITER concern only. Both readers below
# (extract_operator_additions, _extract_managed_body) are deliberately
# dialect-AGNOSTIC and are additionally tolerant of the optional
# "(preserved across updates)" parenthetical, because they run against a target
# whose on-disk fence may predate this change: an installed CLAUDE.md in the
# field carries a markdown fence this writer never emitted. A dialect-pinned
# reader would silently return "" there and DISCARD the operator's additions.
PLAIN_DIALECT = "plain"
MARKDOWN_DIALECT = "markdown"
DEFAULT_DIALECT = PLAIN_DIALECT

MARKER_DIALECTS = {
    PLAIN_DIALECT: {
        "begin_managed": BEGIN_MANAGED,
        "end_managed": END_MANAGED,
        "begin_operator": BEGIN_OPERATOR,
        "end_operator": END_OPERATOR,
        "marker_fmt": "# {key}: {value}",
        "placeholder": DEFAULT_OPERATOR_ADDITIONS_PLACEHOLDER,
    },
    MARKDOWN_DIALECT: {
        "begin_managed": "<!-- === BEGIN MANAGED SECTION (regenerated by update.sh; do not edit) === -->",
        "end_managed": "<!-- === END MANAGED SECTION === -->",
        "begin_operator": "<!-- === BEGIN OPERATOR ADDITIONS (preserved across updates) === -->",
        "end_operator": "<!-- === END OPERATOR ADDITIONS === -->",
        "marker_fmt": "<!-- {key}: {value} -->",
        "placeholder": (
            "<!-- Add workspace-specific guidance below. update.sh preserves this "
            "section verbatim across updates. -->"
        ),
    },
}


def resolve_dialect(dialect: Optional[str]) -> dict:
    """Return the marker table for a dialect name; empty/None resolves to the default.

    Raises ValueError on an unknown non-empty name so a manifest typo fails loudly
    at write time rather than silently emitting the wrong fence.
    """
    name = dialect or DEFAULT_DIALECT
    if name not in MARKER_DIALECTS:
        raise ValueError(
            f"Unknown marker dialect '{name}'; expected one of {sorted(MARKER_DIALECTS)}"
        )
    return MARKER_DIALECTS[name]


# Dialect-agnostic fence matchers. Each accepts the plain (`# === … ===`) and the
# markdown (`<!-- === … === -->`) form, and treats the parenthetical suffix as
# optional so both observed markdown spellings — with and without
# "(preserved across updates)" — are recognized.
_FENCE_OPEN = r"(?:#|<!--)[ \t]*"
_FENCE_CLOSE = r"[ \t]*(?:-->)?[ \t]*"
_PAREN = r"(?:[ \t]*\([^)\n]*\))?"


def _fence_re(label: str) -> str:
    return _FENCE_OPEN + r"===[ \t]*" + label + _PAREN + r"[ \t]*===" + _FENCE_CLOSE


_BEGIN_OPERATOR_RE = _fence_re("BEGIN OPERATOR ADDITIONS")
_END_OPERATOR_RE = _fence_re("END OPERATOR ADDITIONS")
_BEGIN_MANAGED_RE = _fence_re("BEGIN MANAGED SECTION")
_END_MANAGED_RE = _fence_re("END MANAGED SECTION")

FIELD_TO_TOKEN = {
    ("identity", "operator_name"): "[OPERATOR_NAME]",
    ("identity", "operator_email"): "[OPERATOR_EMAIL]",
    ("identity", "operator_git_email"): "[OPERATOR_GIT_EMAIL]",
    ("identity", "operator_github"): "[OPERATOR_GITHUB]",
    ("identity", "operator_phone"): "[OPERATOR_PHONE]",
    ("identity", "operator_role_title"): "[OPERATOR_ROLE_TITLE]",
    ("identity", "operator_organization"): "[OPERATOR_ORGANIZATION]",
    ("paths", "claude_workspace_root"): "[CLAUDE_WORKSPACE_ROOT]",
    ("paths", "operator_homedir_path"): "[OPERATOR_HOMEDIR_PATH]",
    ("paths", "cowork_install_path"): "[COWORK_INSTALL_PATH_BASE]",
}


def parse_toml(path: Path) -> dict:
    """Minimal TOML parser sufficient for operator.toml shape.

    Only handles [section] headers and key = "value" pairs at section scope.
    Does not implement nested tables, arrays, datetimes, or any TOML feature
    operator.toml does not need.
    """
    result: dict[tuple[str, str], str] = {}
    section: Optional[str] = None
    try:
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                if stripped.startswith("[") and stripped.endswith("]"):
                    section = stripped[1:-1].strip()
                    continue
                if "=" in stripped and section is not None:
                    key, _, value = stripped.partition("=")
                    key = key.strip()
                    value = value.strip()
                    if value.startswith('"') and value.endswith('"'):
                        value = value[1:-1].replace("\\\\", "\\").replace('\\"', '"')
                    result[(section, key)] = value
    except FileNotFoundError:
        pass
    return result


# ---- [PMO_PLATFORM_ROOT]: the canonical platform checkout root -------------------------
# Baked into glob patterns in security allowlists, so it must be the DURABLE root: the main
# working tree of the repository the workspace was installed from. The checkout a deploy
# runs from supplies TEMPLATES only. Normative ladder: depersonalization-spec.md §2.
PLATFORM_ROOT_TOKEN = "[PMO_PLATFORM_ROOT]"
INSTALL_RECORD_FIELD = "source_repo_path"                 # written by setup-workspace.sh
INSTALL_RECORD_SOURCE_FIELD = "source_repo_path_source"   # the tier that supplied it
_PLATFORM_MARKER = ("core", "deploy", "compose.py")
_TRANSIENT_WORKTREE_SEGMENT = (".claude", "worktrees")
# The value is substituted into bash `case` glob patterns, so a glob metacharacter or a
# control character would change what the allowlist admits. On POSIX a backslash is the
# pattern's escape character as well; on Windows it is the path separator, so it stays.
_FORBIDDEN_ROOT_CHARS = frozenset("*?[\t\n\r" + ("\\" if os.sep == "/" else ""))
_GIT_ENV_SCRUB = frozenset({
    "GIT_DIR", "GIT_WORK_TREE", "GIT_COMMON_DIR", "GIT_INDEX_FILE", "GIT_OBJECT_DIRECTORY",
    "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_NAMESPACE", "GIT_PREFIX",
    "GIT_CEILING_DIRECTORIES", "GIT_DISCOVERY_ACROSS_FILESYSTEM",
})
_GIT_TIMEOUT_SECONDS = 10
_RECORD_REMEDY = (
    "To record the root, re-run docs/scripts/setup-workspace.sh from the platform checkout "
    "this install should follow, then run ./update.sh --force-regen so every composed "
    "surface is rebuilt on it."
)


class RepoRootUnresolvable(Exception):
    """No tier yielded a valid canonical root; [PMO_PLATFORM_ROOT] must not be substituted."""


class RootResolution(NamedTuple):
    root: str
    source: str             # cli | env | install-record | declared-source | main-worktree
    notes: Tuple[str, ...]  # "NOTE: ..." / "WARN: ..." lines for skipped or rejected tiers


def _git_lines(tree: Path, *args: str) -> Optional[List[str]]:
    env = {k: v for k, v in os.environ.items() if k not in _GIT_ENV_SCRUB}
    try:
        proc = subprocess.run(["git", "-C", str(tree), *args], capture_output=True,
                              stdin=subprocess.DEVNULL, text=True, env=env,
                              timeout=_GIT_TIMEOUT_SECONDS)
    except (OSError, subprocess.SubprocessError, ValueError):
        return None
    return proc.stdout.splitlines() if proc.returncode == 0 else None


def _has_git_entry_at_or_above(tree: Path) -> bool:
    return any((d / ".git").exists() for d in (tree, *tree.parents))


def _same_directory(a: Path, b: Path) -> bool:
    try:
        return os.path.samefile(str(a), str(b))
    except OSError:
        return str(a) == str(b)


def canonical_tree_root(tree: Path) -> Tuple[Optional[Path], str]:
    """(root, kind) for the checkout rooted at `tree`; never a linked worktree's own path.

    kind: main | linked | bare | not-a-repository | unresolvable. Only main (-> the tree
    itself) and linked (-> the repository's main working tree) carry a root. A repository
    git cannot interrogate is `unresolvable`, never `not-a-repository`. Classification is
    by IDENTITY, not membership: a tree that merely sits inside some work tree - a vendored
    copy, or a tree unpacked under a home directory kept in git - is not that work tree,
    so it reads `not-a-repository`.
    """
    tree = Path(os.path.realpath(str(tree)))
    if not tree.is_dir():
        return (None, "unresolvable")
    rev = _git_lines(tree, "rev-parse", "--is-inside-work-tree", "--show-toplevel",
                     "--git-dir", "--git-common-dir")
    if rev is None:
        return (None, "unresolvable" if _has_git_entry_at_or_above(tree) else "not-a-repository")
    if len(rev) != 4 or rev[0].strip() != "true":
        return (None, "unresolvable")
    top = Path(os.path.realpath(rev[1]))
    if not _same_directory(tree, top):
        return (None, "not-a-repository")
    git_dir = Path(os.path.realpath(os.path.join(str(tree), rev[2])))    # may print relative
    common = Path(os.path.realpath(os.path.join(str(tree), rev[3])))
    if git_dir == common:                                                  # ADR-165 discriminator
        return (top, "main")
    block: List[str] = []
    for line in _git_lines(tree, "worktree", "list", "--porcelain") or []:
        if not line.strip():
            break
        block.append(line.strip())
    if not block or not block[0].startswith("worktree "):
        return (None, "unresolvable")
    if "bare" in block[1:]:
        return (None, "bare")
    return (Path(os.path.realpath(block[0][len("worktree "):])), "linked")


def _root_problem(p: Path, *, derived: bool) -> Optional[str]:
    """Why `p` cannot be the canonical root, or None."""
    if not p.is_absolute():
        return "is not an absolute path"
    if any(ch in _FORBIDDEN_ROOT_CHARS for ch in str(p)):
        return ("contains a glob metacharacter, an escape or a control character "
                "(it is substituted into glob patterns)")
    parts = p.parts
    if any(parts[i:i + 2] == _TRANSIENT_WORKTREE_SEGMENT for i in range(len(parts) - 1)):
        return "contains a .claude/worktrees path segment (a transient worktree)"
    if derived:
        if not p.is_dir():
            return "does not exist"
        if not p.joinpath(*_PLATFORM_MARKER).is_file():
            return "is not a pmo-platform checkout (core/deploy/compose.py absent)"
    elif p.is_dir():
        # Membership, not identity: an explicit value that is, or lies inside, a linked
        # worktree is refused. The classifier reads identity, so it is asked about the top
        # level of the work tree that holds the value.
        top = _git_lines(p, "rev-parse", "--show-toplevel")
        main, kind = canonical_tree_root(Path(top[0]) if top and top[0] else p)
        if kind == "linked":
            return f"is a linked worktree; pass its main working tree ({main}) instead"
    return None


def _canonical_declared(tree: Path) -> Tuple[Optional[Path], str]:
    root, kind = canonical_tree_root(tree)
    if kind == "not-a-repository":  # no repository => no worktrees => the tree is its own identity
        return (Path(os.path.realpath(str(tree))), kind)
    return (root, kind)


def _derived_root(tree: Path) -> Tuple[Optional[Path], str, Optional[str]]:
    """Canonicalize a recorded or declared tree and validate it: (root, kind, problem)."""
    if not Path(os.path.realpath(str(tree))).is_dir():
        return (None, "missing", "does not exist")
    root, kind = _canonical_declared(tree)
    if root is None:
        return (None, kind, f"could not be canonicalized ({kind})")
    return (root, kind, _root_problem(root, derived=True))


def _main_worktree_of(origin: Path) -> Tuple[Optional[Path], Optional[str]]:
    """Tier 5: the main working tree of the repository `origin` is a checkout of."""
    root, kind = canonical_tree_root(origin)
    if root is None:
        return (None, f"{origin} has no resolvable main working tree ({kind})")
    problem = _root_problem(root, derived=True)
    if problem:
        return (None, f"its main working tree {root} {problem}")
    return (root, None)


def _read_install_record(state_path: Path) -> Tuple[Optional[Path], str, str]:
    """(recorded root, its provenance label or "", why the record is unusable)."""
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return (None, "", f"no install state at {state_path}")
    except (OSError, ValueError) as err:
        return (None, "", f"install state {state_path} unreadable ({type(err).__name__})")
    if not isinstance(data, dict):
        return (None, "", f"install state {state_path} is not a JSON object")
    value = data.get(INSTALL_RECORD_FIELD)
    if not isinstance(value, str) or not value.strip():
        return (None, "", f"install state {state_path} carries no {INSTALL_RECORD_FIELD}")
    recorded = Path(value).expanduser()
    if not recorded.is_absolute():
        return (None, "", f"recorded {INSTALL_RECORD_FIELD} is not absolute: {value!r}")
    provenance = data.get(INSTALL_RECORD_SOURCE_FIELD)
    return (recorded, provenance.strip() if isinstance(provenance, str) else "", "")


def resolve_repo_root_with_source(
    cli_value: Optional[str] = None, *, install_state: Optional[str] = None,
    declared_source: Optional[str] = None, source_tree: Optional[str] = None,
) -> RootResolution:
    """Resolve [PMO_PLATFORM_ROOT]: the first valid tier wins; no tier => RepoRootUnresolvable.

      1 cli              --repo-root (explicit: validated, never canonicalized)
      2 env              $PMO_PLATFORM_ROOT (explicit: same)
      3 install-record   source_repo_path in the install state file (update time)
      4 declared-source  the checkout an installer declares (install time)
      5 main-worktree    main working tree of the repository `source_tree` is a checkout of
                         (default: this file's checkout — the QUERY ORIGIN, never the value)
    Tiers 3 and 4 are mutually exclusive; 3-5 canonicalize a linked worktree to its main
    working tree; every tier refuses a linked worktree, a .claude/worktrees segment, glob
    metacharacters and control characters (and, on POSIX, a backslash). A record carrying
    source_repo_path_source is honored; a legacy record without it is advisory — used only
    when tier 5 cannot resolve or agrees with it, otherwise one WARN names both roots and
    tier 5 wins. A tree outside any repository resolves only through tier 3 or 4 — never
    through self-location. Tiers 3-5 read the checkout through git, so a checkout git
    cannot interrogate does not resolve, whatever the record says. The token therefore
    never survives unsubstituted: an unresolvable root is an error, not a literal.
    """
    if install_state is not None and declared_source is not None:
        raise ValueError("install_state and declared_source are mutually exclusive")
    notes: List[str] = []

    def explicit(value: str, source: str) -> RootResolution:
        path = Path(value).expanduser().resolve()
        problem = _root_problem(path, derived=False)
        if problem:
            raise RepoRootUnresolvable(f"{source} value {path} {problem}")
        return RootResolution(str(path), source, tuple(notes))

    if cli_value:
        return explicit(cli_value, "cli")
    if os.environ.get("PMO_PLATFORM_ROOT"):
        return explicit(os.environ["PMO_PLATFORM_ROOT"], "env")

    origin = Path(source_tree) if source_tree else Path(__file__).resolve().parents[2]

    if install_state is not None:
        recorded, provenance, why = _read_install_record(Path(install_state))
        if recorded is None:
            notes.append(f"NOTE: install-record tier skipped: {why}")
        else:
            root, kind, problem = _derived_root(recorded)
            if problem is not None or root is None:
                notes.append(f"WARN: recorded root {recorded} rejected: {problem}. {_RECORD_REMEDY}")
            elif provenance:
                if kind == "linked":
                    notes.append(f"NOTE: recorded root {recorded} is a linked worktree; "
                                 f"using its main working tree {root}")
                here, _ = canonical_tree_root(origin)
                if here is not None and here != root:
                    notes.append(f"NOTE: this checkout belongs to {here}; "
                                 f"[PMO_PLATFORM_ROOT] comes from the install record ({root})")
                return RootResolution(str(root), "install-record", tuple(notes))
            else:
                # A legacy record, written raw by an installer that recorded no provenance.
                current, current_problem = _main_worktree_of(origin)
                if current is None:
                    notes.append(f"NOTE: legacy install record {recorded} is used: it carries no "
                                 f"{INSTALL_RECORD_SOURCE_FIELD}, and the main-worktree tier "
                                 f"cannot resolve ({current_problem})")
                    return RootResolution(str(root), "install-record", tuple(notes))
                if current == root:
                    notes.append(f"NOTE: legacy install record {recorded} carries no "
                                 f"{INSTALL_RECORD_SOURCE_FIELD}; it agrees with the main "
                                 "working tree, so it is used")
                    return RootResolution(str(root), "install-record", tuple(notes))
                notes.append(f"WARN: legacy install record ignored: it names {root} and carries "
                             f"no {INSTALL_RECORD_SOURCE_FIELD}, while this checkout's main "
                             f"working tree is {current}, so [PMO_PLATFORM_ROOT] resolves to "
                             f"{current}. {_RECORD_REMEDY}")
                return RootResolution(str(current), "main-worktree", tuple(notes))

    if declared_source is not None:
        root, kind, problem = _derived_root(Path(declared_source))
        if problem is not None or root is None:
            raise RepoRootUnresolvable(f"declared source {declared_source} {problem}")
        return RootResolution(str(root), "declared-source", tuple(notes))

    root, problem = _main_worktree_of(origin)
    if root is None:
        raise RepoRootUnresolvable("; ".join(notes + [f"main-worktree tier: {problem}"]))
    return RootResolution(str(root), "main-worktree", tuple(notes))


def resolve_repo_root(cli_value: Optional[str] = None, **tiers: Optional[str]) -> str:
    """Backward-compatible wrapper returning only the root. Raises RepoRootUnresolvable."""
    return resolve_repo_root_with_source(cli_value, **tiers).root


def resolve_tokens(
    operator_toml_path: Path,
    override_toml_path: Optional[Path] = None,
    repo_root: Optional[str] = None,
    *,
    install_state: Optional[str] = None,
    need_repo_root: bool = True,
) -> dict[str, str]:
    """Resolve operator.toml (+ optional override) into the token dictionary the primitives consume.

    [PMO_PLATFORM_ROOT] is resolved only when `need_repo_root` is set — the writers pass
    False for a template that does not carry the token, so a token-free write never
    depends on git. Direct callers keep the eager default. Raises RepoRootUnresolvable.
    """
    token_values: dict[str, str] = {}
    sources = [operator_toml_path]
    if override_toml_path is not None:
        sources.append(override_toml_path)
    for path in sources:
        if not path or not path.is_file():
            continue
        parsed = parse_toml(path)
        for (section, key), token in FIELD_TO_TOKEN.items():
            value = parsed.get((section, key))
            if value is None or value == "":
                continue
            token_values[token] = value

    if "[OPERATOR_NAME]" in token_values and "[OPERATOR_FIRST_NAME]" not in token_values:
        full_name = token_values["[OPERATOR_NAME]"]
        token_values["[OPERATOR_FIRST_NAME]"] = full_name.split()[0] if full_name else ""

    home = os.environ.get("HOME", "")
    token_values.setdefault("[OPERATOR_HOMEDIR_PATH]", home)
    token_values.setdefault("[CLAUDE_WORKSPACE_ROOT]", os.path.join(home, "Claude"))
    # An `if`, not setdefault: setdefault evaluates its default on every call, which
    # would make every write depend on git whether or not its template needs the root.
    if need_repo_root and PLATFORM_ROOT_TOKEN not in token_values:
        token_values[PLATFORM_ROOT_TOKEN] = resolve_repo_root(repo_root, install_state=install_state)
    return token_values


def extract_operator_additions(target_path: Path) -> str:
    """Return the verbatim content between BEGIN/END OPERATOR ADDITIONS markers.

    Returns the empty string if the target file does not exist, or exists but has no markers.
    Trailing whitespace on the captured content is stripped (the END marker is on its own line).

    Dialect-agnostic and parenthetical-tolerant (ADR-122): matches the plain
    `# === … ===` form and the markdown `<!-- === … === -->` form, with or
    without the "(preserved across updates)" suffix. A dialect-pinned reader
    would return "" on an installed markdown-fenced target and silently discard
    the operator's additions on the next regeneration.
    """
    if not target_path.is_file():
        return ""
    text = target_path.read_text(encoding="utf-8")
    match = re.search(
        _BEGIN_OPERATOR_RE + r"\n(.*?)\n" + _END_OPERATOR_RE,
        text,
        re.DOTALL,
    )
    if not match:
        return ""
    return match.group(1).rstrip()


# Marker-line identifiers carried inside the MANAGED fence. Excluded from the
# tamper-anchor body domain so a marker rewrite (new managed_at on every regen)
# never reads as tampering.
_MARKER_KEYS = ("managed_sha", "installed_sha", "managed_at")


def _strip_marker_wrapper(stripped_line: str) -> str:
    """Return the marker payload of a fence line, comment-wrapper removed.

    Handles both the plain-text form (`# managed_sha: <hex>`) and the markdown
    form (`<!-- managed_sha: <hex> -->`). Returns the inner text (e.g.
    `managed_sha: <hex>`) so the caller can test it against _MARKER_KEYS.
    """
    s = stripped_line
    if s.startswith("<!--") and s.endswith("-->"):
        s = s[len("<!--"):-len("-->")].strip()
    if s.startswith("#"):
        s = s[1:].strip()
    return s


def _is_marker_line(line: str) -> bool:
    payload = _strip_marker_wrapper(line.strip())
    return any(payload.startswith(f"{key}:") for key in _MARKER_KEYS)


def _extract_managed_body(text: str) -> str:
    """Return the installed managed-section body — the canonical tamper-anchor domain.

    The body is the region between BEGIN_MANAGED and END_MANAGED with the three
    marker lines (managed_sha / installed_sha / managed_at, in either the plain
    `#` or markdown `<!-- -->` form) removed and the trailing newline stripped.

    This is defined to equal `content.rstrip()` on a file freshly written by
    write_managed_file (the round-trip invariant). It is the single byte-domain
    definition the writer and the `installed-sha` reader both consume, so the
    hash a writer stores and the hash a reader computes cannot drift.

    Returns "" when there is no MANAGED fence or the fence body is empty.

    Dialect-agnostic (ADR-122): recognizes the plain and markdown fence forms, so
    the tamper anchor of a markdown-fenced target is computed over the same
    byte-domain the writer emitted rather than reading as "no fence".
    """
    match = re.search(
        _BEGIN_MANAGED_RE + r"\n(.*?)\n" + _END_MANAGED_RE,
        text,
        re.DOTALL,
    )
    if not match:
        return ""
    inner = match.group(1)
    body_lines = [ln for ln in inner.split("\n") if not _is_marker_line(ln)]
    return "\n".join(body_lines).rstrip()


def installed_sha_of(target_path: Path) -> str:
    """Return the SHA-256 hex digest of the installed managed body (the tamper anchor).

    Returns "" when the target does not exist, has no MANAGED fence, or the
    fence body is empty. Callers (update.sh) treat "" as "unknown, not tampered"
    — the self-healing back-compat path for installs predating the marker.
    """
    if not target_path.is_file():
        return ""
    body = _extract_managed_body(target_path.read_text(encoding="utf-8"))
    if body == "":
        return ""
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def write_managed_file(
    source_path: Path,
    target_path: Path,
    tokens: dict[str, str],
    preserved_additions: str,
    source_sha: str,
    tokens_flag: str,
    dialect: Optional[str] = None,
) -> None:
    """Compose and atomically write a marker-fenced file.

    Args:
        source_path: Source template inside the repo.
        target_path: Runtime destination (overwritten atomically).
        tokens: Map of [TOKEN] -> substituted value.
        preserved_additions: Verbatim content for the OPERATOR ADDITIONS section.
            If empty, a default invitation comment is emitted instead.
        source_sha: SHA of the source content; recorded as managed_sha in the output.
        tokens_flag: "tokens" to perform substitution, "raw" to copy template content verbatim.
        dialect: Marker dialect ("plain" | "markdown"); None/empty resolves to "plain".
    """
    markers = resolve_dialect(dialect)
    content = source_path.read_text(encoding="utf-8")

    if tokens_flag == "tokens":
        for token, value in tokens.items():
            if value is None:
                continue
            content = content.replace(token, str(value))
        # The survival guard, checked before anything is written: an unresolved root must
        # fail the write, never reach a security allowlist as a literal (where the bracketed
        # token would read as a glob bracket expression).
        if PLATFORM_ROOT_TOKEN in content:
            raise RepoRootUnresolvable(
                f"{PLATFORM_ROOT_TOKEN} survived substitution in {source_path}; "
                f"refusing to write {target_path}"
            )

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    additions_body = preserved_additions if preserved_additions else markers["placeholder"]

    # managed_body is the exact post-substitution body string emitted below; its
    # SHA is the tamper anchor (installed_sha). Distinct from source_sha
    # (managed_sha), which is the pre-substitution source-template hash. See
    # ADR-014. Marker order is fixed: managed_sha -> installed_sha -> managed_at.
    managed_body = content.rstrip()
    installed_sha = hashlib.sha256(managed_body.encode("utf-8")).hexdigest()
    marker = markers["marker_fmt"].format

    lines = [
        markers["begin_managed"],
        marker(key="managed_sha", value=source_sha),
        marker(key="installed_sha", value=installed_sha),
        marker(key="managed_at", value=timestamp),
        managed_body,
        markers["end_managed"],
        "",
        markers["begin_operator"],
        additions_body,
        markers["end_operator"],
        "",
    ]

    tmp_path = target_path.with_suffix(target_path.suffix + ".tmp")
    tmp_path.write_text("\n".join(lines), encoding="utf-8")
    os.replace(tmp_path, target_path)


def _template_needs_root(source_path: Path, tokens_flag: str) -> bool:
    """Lazy resolution: only a tokens-substituted template carrying the token needs the root."""
    return tokens_flag == "tokens" and PLATFORM_ROOT_TOKEN in source_path.read_text(encoding="utf-8")


def regen_one_file(
    source_path: Path,
    target_path: Path,
    operator_toml_path: Path,
    override_toml_path: Optional[Path],
    tokens_flag: str,
    source_sha: str,
    repo_root: Optional[str] = None,
    dialect: Optional[str] = None,
) -> None:
    """Extract OPERATOR ADDITIONS from current target, then write new target with them preserved."""
    preserved = extract_operator_additions(target_path)
    tokens = resolve_tokens(operator_toml_path, override_toml_path, repo_root,
                            need_repo_root=_template_needs_root(source_path, tokens_flag))
    write_managed_file(
        source_path, target_path, tokens, preserved, source_sha, tokens_flag, dialect
    )


def _read_preserved(path: Optional[str]) -> str:
    if not path:
        return ""
    return Path(path).read_text(encoding="utf-8").rstrip()


def _cli_extract(args: argparse.Namespace) -> int:
    sys.stdout.write(extract_operator_additions(Path(args.target)))
    return 0


def _cli_installed_sha(args: argparse.Namespace) -> int:
    # The tamper anchor of an installed file: SHA-256 of its managed body.
    # Prints "" (exit 0) when the file is absent / has no fence / has an empty
    # body, so update.sh can treat absence as "unknown, not tampered".
    sys.stdout.write(installed_sha_of(Path(args.target)))
    return 0


def _cli_write(args: argparse.Namespace) -> int:
    tokens = resolve_tokens(
        Path(args.operator_toml),
        Path(args.override_toml) if args.override_toml else None,
        args.repo_root or None,
        need_repo_root=_template_needs_root(Path(args.source), args.tokens_flag),
    )
    write_managed_file(
        source_path=Path(args.source),
        target_path=Path(args.target),
        tokens=tokens,
        preserved_additions=_read_preserved(args.preserved_additions_file),
        source_sha=args.source_sha,
        tokens_flag=args.tokens_flag,
        dialect=args.dialect or None,
    )
    return 0


def _cli_regen(args: argparse.Namespace) -> int:
    regen_one_file(
        source_path=Path(args.source),
        target_path=Path(args.target),
        operator_toml_path=Path(args.operator_toml),
        override_toml_path=Path(args.override_toml) if args.override_toml else None,
        tokens_flag=args.tokens_flag,
        source_sha=args.source_sha,
        repo_root=args.repo_root or None,
        dialect=args.dialect or None,
    )
    return 0


def _cli_resolve_root(args: argparse.Namespace) -> int:
    # NOTE:/WARN: lines go to stderr; the one value line goes to stdout, so a caller
    # capturing stdout gets exactly "<root>\t<tier>" and the notes still reach the operator.
    res = resolve_repo_root_with_source(
        args.repo_root or None,
        install_state=args.install_state or None,
        declared_source=args.declare_source or None,
        source_tree=args.source_tree or None,
    )
    for note in res.notes:
        sys.stderr.write(note + "\n")
    sys.stdout.write(f"{res.root}\t{res.source}\n")
    return 0


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "compose.py")
    subparsers = parser.add_subparsers(dest="command", required=True)

    ext = subparsers.add_parser("extract", help="Extract OPERATOR ADDITIONS section from a target file")
    ext.add_argument("--target", required=True)
    ext.set_defaults(func=_cli_extract)

    ish = subparsers.add_parser(
        "installed-sha",
        help="Print SHA-256 of the installed managed body (tamper anchor); empty if no fence/body",
    )
    ish.add_argument("--target", required=True)
    ish.set_defaults(func=_cli_installed_sha)

    common_write_args = lambda p: (
        p.add_argument("--source", required=True),
        p.add_argument("--target", required=True),
        p.add_argument("--operator-toml", required=True),
        p.add_argument("--override-toml", default=""),
        p.add_argument("--tokens-flag", choices=["tokens", "raw"], required=True),
        p.add_argument("--source-sha", required=True),
        p.add_argument(
            "--repo-root",
            default="",
            help="Repo root for the [PMO_PLATFORM_ROOT] token (consulted only when the "
                 "template carries it). Precedence: this flag > $PMO_PLATFORM_ROOT > the "
                 "main working tree of the repository containing this compose.py > error; "
                 "a linked worktree never supplies it. update.sh and setup-workspace.sh "
                 "resolve the install root once (resolve-root) and pass it here.",
        ),
        p.add_argument(
            "--dialect",
            default="",
            choices=["", PLAIN_DIALECT, MARKDOWN_DIALECT],
            help="Marker dialect for the emitted fence (ADR-122). Empty (the "
                 "default) resolves to 'plain', so callers that omit it keep "
                 "byte-identical output. Readers are dialect-agnostic; this "
                 "selects only what the writer emits.",
        ),
    )

    wrt = subparsers.add_parser("write", help="Write a managed file with provided preserved-additions")
    common_write_args(wrt)
    wrt.add_argument("--preserved-additions-file", default="")
    wrt.set_defaults(func=_cli_write)

    rgn = subparsers.add_parser("regen", help="Extract from target then write (convenience for update flow)")
    common_write_args(rgn)
    rgn.set_defaults(func=_cli_regen)

    rrt = subparsers.add_parser(
        "resolve-root",
        help="Print the canonical [PMO_PLATFORM_ROOT] value and the tier that supplied it, "
             "tab-separated; exit 3 when no tier yields a valid root",
    )
    rrt.add_argument("--repo-root", default="", help="Explicit root (tier 1)")
    record = rrt.add_mutually_exclusive_group()
    record.add_argument("--install-state", default="", metavar="FILE",
                        help="Update time: the workspace's install state file (tier 3)")
    record.add_argument("--declare-source", default="", metavar="DIR",
                        help="Install time: the checkout being installed from (tier 4)")
    rrt.add_argument("--source-tree", default="", metavar="DIR",
                     help="The tier-5 query origin (default: the checkout holding this compose.py)")
    rrt.set_defaults(func=_cli_resolve_root)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except RepoRootUnresolvable as err:
        sys.stderr.write(f"ERROR: cannot resolve [PMO_PLATFORM_ROOT]: {err}\n")
        return 3


if __name__ == "__main__":
    sys.exit(main())
