#!/usr/bin/env python3
"""Composition-surface write primitive — single source of truth for marker-fenced file composition.

Exposes Pattern C primitives: extract_operator_additions (pure read) and
write_managed_file (pure write). These replace the duplicated Python heredocs
previously embedded in update.sh and docs/scripts/setup-workspace.sh.

Spec: core/standards/composition-surface-spec.md §2-§3 (marker syntax, regeneration semantics).
Token vocabulary: core/standards/depersonalization-spec.md §1.

Two-hash separation (ADR-014): the MANAGED fence carries two SHA markers.
`managed_sha` is the SHA of the source template (pre-substitution) — the
regeneration trigger. `installed_sha` is the SHA of the post-substitution
installed managed body (the exact bytes this writer emits as the body) — the
tamper-detection anchor. They differ by design for token-bearing files (the
installed body is token-substituted), so tamper detection MUST compare against
`installed_sha`, never `managed_sha`. `_extract_managed_body` defines the
canonical body byte-domain shared by the writer (`write_managed_file`) and the
reader (the `installed-sha` subcommand), so the two cannot drift.

Public API (Python):
    extract_operator_additions(target_path) -> str
    write_managed_file(source_path, target_path, tokens, preserved_additions,
                       source_sha, tokens_flag) -> None
    regen_one_file(source_path, target_path, operator_toml_path,
                   override_toml_path, tokens_flag, source_sha) -> None
    installed_sha_of(target_path) -> str   # tamper anchor of an installed file ("" if no fence/body)

CLI:
    extract       --target <path>
    write         --source <path> --target <path> --operator-toml <path>
                  [--override-toml <path>] --tokens-flag {tokens,raw}
                  --source-sha <sha> [--preserved-additions-file <path>]
                  [--dialect {plain,markdown}]
    regen         --source <path> --target <path> --operator-toml <path>
                  [--override-toml <path>] --tokens-flag {tokens,raw} --source-sha <sha>
                  [--dialect {plain,markdown}]
    installed-sha --target <path>          # hex digest of the installed managed body ("" if none)

Marker dialects (ADR-122): the writer emits the fence in the dialect the target's
manifest row declares — `plain` (comment-prefixed) or `markdown` (HTML-comment).
`plain` is the default, so a caller that passes no dialect gets byte-identical
output to the pre-ADR-122 writer. Both readers are dialect-AGNOSTIC by design.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

BEGIN_MANAGED = "# === BEGIN MANAGED SECTION (regenerated by update.sh; do not edit) ==="
END_MANAGED = "# === END MANAGED SECTION ==="
BEGIN_OPERATOR = "# === BEGIN OPERATOR ADDITIONS (preserved across updates) ==="
END_OPERATOR = "# === END OPERATOR ADDITIONS ==="

DEFAULT_OPERATOR_ADDITIONS_PLACEHOLDER = (
    "# Add custom entries below. update.sh never touches this section."
)

# --- Marker dialects (ADR-122) ---------------------------------------------
# A composition-surface target's fence is emitted in the dialect its manifest
# row declares. `plain` is the comment-prefixed form used by every allowlist,
# mode file, and .toml/.txt surface; `markdown` is the HTML-comment form the
# spec defines for markdown surfaces (§2.2). `plain` is the DEFAULT: a manifest
# row that omits the dialect field resolves to it, so every pre-ADR-122 row is
# unchanged and un-rewritten.
#
# The dialect is a WRITER concern only. Both readers below
# (extract_operator_additions, _extract_managed_body) are deliberately
# dialect-AGNOSTIC and are additionally tolerant of the optional
# "(preserved across updates)" parenthetical, because they run against a target
# whose on-disk fence may predate this change: an installed CLAUDE.md in the
# field carries a markdown fence this writer never emitted. A dialect-pinned
# reader would silently return "" there and DISCARD the operator's additions.
PLAIN_DIALECT = "plain"
MARKDOWN_DIALECT = "markdown"
DEFAULT_DIALECT = PLAIN_DIALECT

MARKER_DIALECTS = {
    PLAIN_DIALECT: {
        "begin_managed": BEGIN_MANAGED,
        "end_managed": END_MANAGED,
        "begin_operator": BEGIN_OPERATOR,
        "end_operator": END_OPERATOR,
        "marker_fmt": "# {key}: {value}",
        "placeholder": DEFAULT_OPERATOR_ADDITIONS_PLACEHOLDER,
    },
    MARKDOWN_DIALECT: {
        "begin_managed": "<!-- === BEGIN MANAGED SECTION (regenerated by update.sh; do not edit) === -->",
        "end_managed": "<!-- === END MANAGED SECTION === -->",
        "begin_operator": "<!-- === BEGIN OPERATOR ADDITIONS (preserved across updates) === -->",
        "end_operator": "<!-- === END OPERATOR ADDITIONS === -->",
        "marker_fmt": "<!-- {key}: {value} -->",
        "placeholder": (
            "<!-- Add workspace-specific guidance below. update.sh preserves this "
            "section verbatim across updates. -->"
        ),
    },
}


def resolve_dialect(dialect: Optional[str]) -> dict:
    """Return the marker table for a dialect name; empty/None resolves to the default.

    Raises ValueError on an unknown non-empty name so a manifest typo fails loudly
    at write time rather than silently emitting the wrong fence.
    """
    name = dialect or DEFAULT_DIALECT
    if name not in MARKER_DIALECTS:
        raise ValueError(
            f"Unknown marker dialect '{name}'; expected one of {sorted(MARKER_DIALECTS)}"
        )
    return MARKER_DIALECTS[name]


# Dialect-agnostic fence matchers. Each accepts the plain (`# === … ===`) and the
# markdown (`<!-- === … === -->`) form, and treats the parenthetical suffix as
# optional so both observed markdown spellings — with and without
# "(preserved across updates)" — are recognized.
_FENCE_OPEN = r"(?:#|<!--)[ \t]*"
_FENCE_CLOSE = r"[ \t]*(?:-->)?[ \t]*"
_PAREN = r"(?:[ \t]*\([^)\n]*\))?"


def _fence_re(label: str) -> str:
    return _FENCE_OPEN + r"===[ \t]*" + label + _PAREN + r"[ \t]*===" + _FENCE_CLOSE


_BEGIN_OPERATOR_RE = _fence_re("BEGIN OPERATOR ADDITIONS")
_END_OPERATOR_RE = _fence_re("END OPERATOR ADDITIONS")
_BEGIN_MANAGED_RE = _fence_re("BEGIN MANAGED SECTION")
_END_MANAGED_RE = _fence_re("END MANAGED SECTION")

FIELD_TO_TOKEN = {
    ("identity", "operator_name"): "[OPERATOR_NAME]",
    ("identity", "operator_email"): "[OPERATOR_EMAIL]",
    ("identity", "operator_git_email"): "[OPERATOR_GIT_EMAIL]",
    ("identity", "operator_github"): "[OPERATOR_GITHUB]",
    ("identity", "operator_phone"): "[OPERATOR_PHONE]",
    ("identity", "operator_role_title"): "[OPERATOR_ROLE_TITLE]",
    ("identity", "operator_organization"): "[OPERATOR_ORGANIZATION]",
    ("paths", "claude_workspace_root"): "[CLAUDE_WORKSPACE_ROOT]",
    ("paths", "operator_homedir_path"): "[OPERATOR_HOMEDIR_PATH]",
    ("paths", "cowork_install_path"): "[COWORK_INSTALL_PATH_BASE]",
}


def parse_toml(path: Path) -> dict:
    """Minimal TOML parser sufficient for operator.toml shape.

    Only handles [section] headers and key = "value" pairs at section scope.
    Does not implement nested tables, arrays, datetimes, or any TOML feature
    operator.toml does not need.
    """
    result: dict[tuple[str, str], str] = {}
    section: Optional[str] = None
    try:
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                if stripped.startswith("[") and stripped.endswith("]"):
                    section = stripped[1:-1].strip()
                    continue
                if "=" in stripped and section is not None:
                    key, _, value = stripped.partition("=")
                    key = key.strip()
                    value = value.strip()
                    if value.startswith('"') and value.endswith('"'):
                        value = value[1:-1].replace("\\\\", "\\").replace('\\"', '"')
                    result[(section, key)] = value
    except FileNotFoundError:
        pass
    return result


def resolve_repo_root(cli_value: Optional[str] = None) -> str:
    """Resolve the pmo-platform repo root for the [PMO_PLATFORM_ROOT] token.

    Precedence (mirrors resolve_workspace_root in
    core/deploy/tools/check-doc-links.py):
      1. cli_value          — explicit --repo-root (sandboxed tests / overrides)
      2. PMO_PLATFORM_ROOT   — env override
      3. self-location       — Path(__file__).resolve().parents[2]

    Tier 3 is the install-safety anchor: compose.py lives at
    <repo>/core/deploy/compose.py and is never copied out of the repo (it is not
    a composition surface), so parents[2] is ALWAYS the repo root being composed
    — at install time (setup-workspace.sh sources the lib from --source-repo) and
    at update time (update.sh from its own repo root) alike. Because this tier can
    never be absent, the [PMO_PLATFORM_ROOT] token can never survive
    unsubstituted into a deployed file.
    """
    if cli_value:
        return str(Path(cli_value).expanduser().resolve())
    env_value = os.environ.get("PMO_PLATFORM_ROOT")
    if env_value:
        return str(Path(env_value).expanduser().resolve())
    return str(Path(__file__).resolve().parents[2])


def resolve_tokens(
    operator_toml_path: Path,
    override_toml_path: Optional[Path] = None,
    repo_root: Optional[str] = None,
) -> dict[str, str]:
    """Resolve operator.toml (+ optional override) into the token dictionary the primitives consume."""
    token_values: dict[str, str] = {}
    sources = [operator_toml_path]
    if override_toml_path is not None:
        sources.append(override_toml_path)
    for path in sources:
        if not path or not path.is_file():
            continue
        parsed = parse_toml(path)
        for (section, key), token in FIELD_TO_TOKEN.items():
            value = parsed.get((section, key))
            if value is None or value == "":
                continue
            token_values[token] = value

    if "[OPERATOR_NAME]" in token_values and "[OPERATOR_FIRST_NAME]" not in token_values:
        full_name = token_values["[OPERATOR_NAME]"]
        token_values["[OPERATOR_FIRST_NAME]"] = full_name.split()[0] if full_name else ""

    home = os.environ.get("HOME", "")
    token_values.setdefault("[OPERATOR_HOMEDIR_PATH]", home)
    token_values.setdefault("[CLAUDE_WORKSPACE_ROOT]", os.path.join(home, "Claude"))
    token_values.setdefault("[PMO_PLATFORM_ROOT]", resolve_repo_root(repo_root))
    return token_values


def extract_operator_additions(target_path: Path) -> str:
    """Return the verbatim content between BEGIN/END OPERATOR ADDITIONS markers.

    Returns the empty string if the target file does not exist, or exists but has no markers.
    Trailing whitespace on the captured content is stripped (the END marker is on its own line).

    Dialect-agnostic and parenthetical-tolerant (ADR-122): matches the plain
    `# === … ===` form and the markdown `<!-- === … === -->` form, with or
    without the "(preserved across updates)" suffix. A dialect-pinned reader
    would return "" on an installed markdown-fenced target and silently discard
    the operator's additions on the next regeneration.
    """
    if not target_path.is_file():
        return ""
    text = target_path.read_text(encoding="utf-8")
    match = re.search(
        _BEGIN_OPERATOR_RE + r"\n(.*?)\n" + _END_OPERATOR_RE,
        text,
        re.DOTALL,
    )
    if not match:
        return ""
    return match.group(1).rstrip()


# Marker-line identifiers carried inside the MANAGED fence. Excluded from the
# tamper-anchor body domain so a marker rewrite (new managed_at on every regen)
# never reads as tampering.
_MARKER_KEYS = ("managed_sha", "installed_sha", "managed_at")


def _strip_marker_wrapper(stripped_line: str) -> str:
    """Return the marker payload of a fence line, comment-wrapper removed.

    Handles both the plain-text form (`# managed_sha: <hex>`) and the markdown
    form (`<!-- managed_sha: <hex> -->`). Returns the inner text (e.g.
    `managed_sha: <hex>`) so the caller can test it against _MARKER_KEYS.
    """
    s = stripped_line
    if s.startswith("<!--") and s.endswith("-->"):
        s = s[len("<!--"):-len("-->")].strip()
    if s.startswith("#"):
        s = s[1:].strip()
    return s


def _is_marker_line(line: str) -> bool:
    payload = _strip_marker_wrapper(line.strip())
    return any(payload.startswith(f"{key}:") for key in _MARKER_KEYS)


def _extract_managed_body(text: str) -> str:
    """Return the installed managed-section body — the canonical tamper-anchor domain.

    The body is the region between BEGIN_MANAGED and END_MANAGED with the three
    marker lines (managed_sha / installed_sha / managed_at, in either the plain
    `#` or markdown `<!-- -->` form) removed and the trailing newline stripped.

    This is defined to equal `content.rstrip()` on a file freshly written by
    write_managed_file (the round-trip invariant). It is the single byte-domain
    definition the writer and the `installed-sha` reader both consume, so the
    hash a writer stores and the hash a reader computes cannot drift.

    Returns "" when there is no MANAGED fence or the fence body is empty.

    Dialect-agnostic (ADR-122): recognizes the plain and markdown fence forms, so
    the tamper anchor of a markdown-fenced target is computed over the same
    byte-domain the writer emitted rather than reading as "no fence".
    """
    match = re.search(
        _BEGIN_MANAGED_RE + r"\n(.*?)\n" + _END_MANAGED_RE,
        text,
        re.DOTALL,
    )
    if not match:
        return ""
    inner = match.group(1)
    body_lines = [ln for ln in inner.split("\n") if not _is_marker_line(ln)]
    return "\n".join(body_lines).rstrip()


def installed_sha_of(target_path: Path) -> str:
    """Return the SHA-256 hex digest of the installed managed body (the tamper anchor).

    Returns "" when the target does not exist, has no MANAGED fence, or the
    fence body is empty. Callers (update.sh) treat "" as "unknown, not tampered"
    — the self-healing back-compat path for installs predating the marker.
    """
    if not target_path.is_file():
        return ""
    body = _extract_managed_body(target_path.read_text(encoding="utf-8"))
    if body == "":
        return ""
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def write_managed_file(
    source_path: Path,
    target_path: Path,
    tokens: dict[str, str],
    preserved_additions: str,
    source_sha: str,
    tokens_flag: str,
    dialect: Optional[str] = None,
) -> None:
    """Compose and atomically write a marker-fenced file.

    Args:
        source_path: Source template inside the repo.
        target_path: Runtime destination (overwritten atomically).
        tokens: Map of [TOKEN] -> substituted value.
        preserved_additions: Verbatim content for the OPERATOR ADDITIONS section.
            If empty, a default invitation comment is emitted instead.
        source_sha: SHA of the source content; recorded as managed_sha in the output.
        tokens_flag: "tokens" to perform substitution, "raw" to copy template content verbatim.
        dialect: Marker dialect ("plain" | "markdown"); None/empty resolves to "plain".
    """
    markers = resolve_dialect(dialect)
    content = source_path.read_text(encoding="utf-8")

    if tokens_flag == "tokens":
        for token, value in tokens.items():
            if value is None:
                continue
            content = content.replace(token, str(value))

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    additions_body = preserved_additions if preserved_additions else markers["placeholder"]

    # managed_body is the exact post-substitution body string emitted below; its
    # SHA is the tamper anchor (installed_sha). Distinct from source_sha
    # (managed_sha), which is the pre-substitution source-template hash. See
    # ADR-014. Marker order is fixed: managed_sha -> installed_sha -> managed_at.
    managed_body = content.rstrip()
    installed_sha = hashlib.sha256(managed_body.encode("utf-8")).hexdigest()
    marker = markers["marker_fmt"].format

    lines = [
        markers["begin_managed"],
        marker(key="managed_sha", value=source_sha),
        marker(key="installed_sha", value=installed_sha),
        marker(key="managed_at", value=timestamp),
        managed_body,
        markers["end_managed"],
        "",
        markers["begin_operator"],
        additions_body,
        markers["end_operator"],
        "",
    ]

    tmp_path = target_path.with_suffix(target_path.suffix + ".tmp")
    tmp_path.write_text("\n".join(lines), encoding="utf-8")
    os.replace(tmp_path, target_path)


def regen_one_file(
    source_path: Path,
    target_path: Path,
    operator_toml_path: Path,
    override_toml_path: Optional[Path],
    tokens_flag: str,
    source_sha: str,
    repo_root: Optional[str] = None,
    dialect: Optional[str] = None,
) -> None:
    """Extract OPERATOR ADDITIONS from current target, then write new target with them preserved."""
    preserved = extract_operator_additions(target_path)
    tokens = resolve_tokens(operator_toml_path, override_toml_path, repo_root)
    write_managed_file(
        source_path, target_path, tokens, preserved, source_sha, tokens_flag, dialect
    )


def _read_preserved(path: Optional[str]) -> str:
    if not path:
        return ""
    return Path(path).read_text(encoding="utf-8").rstrip()


def _cli_extract(args: argparse.Namespace) -> int:
    sys.stdout.write(extract_operator_additions(Path(args.target)))
    return 0


def _cli_installed_sha(args: argparse.Namespace) -> int:
    # The tamper anchor of an installed file: SHA-256 of its managed body.
    # Prints "" (exit 0) when the file is absent / has no fence / has an empty
    # body, so update.sh can treat absence as "unknown, not tampered".
    sys.stdout.write(installed_sha_of(Path(args.target)))
    return 0


def _cli_write(args: argparse.Namespace) -> int:
    tokens = resolve_tokens(
        Path(args.operator_toml),
        Path(args.override_toml) if args.override_toml else None,
        args.repo_root or None,
    )
    write_managed_file(
        source_path=Path(args.source),
        target_path=Path(args.target),
        tokens=tokens,
        preserved_additions=_read_preserved(args.preserved_additions_file),
        source_sha=args.source_sha,
        tokens_flag=args.tokens_flag,
        dialect=args.dialect or None,
    )
    return 0


def _cli_regen(args: argparse.Namespace) -> int:
    regen_one_file(
        source_path=Path(args.source),
        target_path=Path(args.target),
        operator_toml_path=Path(args.operator_toml),
        override_toml_path=Path(args.override_toml) if args.override_toml else None,
        tokens_flag=args.tokens_flag,
        source_sha=args.source_sha,
        repo_root=args.repo_root or None,
        dialect=args.dialect or None,
    )
    return 0


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "compose.py")
    subparsers = parser.add_subparsers(dest="command", required=True)

    ext = subparsers.add_parser("extract", help="Extract OPERATOR ADDITIONS section from a target file")
    ext.add_argument("--target", required=True)
    ext.set_defaults(func=_cli_extract)

    ish = subparsers.add_parser(
        "installed-sha",
        help="Print SHA-256 of the installed managed body (tamper anchor); empty if no fence/body",
    )
    ish.add_argument("--target", required=True)
    ish.set_defaults(func=_cli_installed_sha)

    common_write_args = lambda p: (
        p.add_argument("--source", required=True),
        p.add_argument("--target", required=True),
        p.add_argument("--operator-toml", required=True),
        p.add_argument("--override-toml", default=""),
        p.add_argument("--tokens-flag", choices=["tokens", "raw"], required=True),
        p.add_argument("--source-sha", required=True),
        p.add_argument(
            "--repo-root",
            default="",
            help="Repo root for the [PMO_PLATFORM_ROOT] token. Precedence: this "
                 "flag > $PMO_PLATFORM_ROOT > compose.py self-location "
                 "(parents[2]). Default (empty) uses self-location, which is "
                 "correct for every real install/update invocation.",
        ),
        p.add_argument(
            "--dialect",
            default="",
            choices=["", PLAIN_DIALECT, MARKDOWN_DIALECT],
            help="Marker dialect for the emitted fence (ADR-122). Empty (the "
                 "default) resolves to 'plain', so callers that omit it keep "
                 "byte-identical output. Readers are dialect-agnostic; this "
                 "selects only what the writer emits.",
        ),
    )

    wrt = subparsers.add_parser("write", help="Write a managed file with provided preserved-additions")
    common_write_args(wrt)
    wrt.add_argument("--preserved-additions-file", default="")
    wrt.set_defaults(func=_cli_write)

    rgn = subparsers.add_parser("regen", help="Extract from target then write (convenience for update flow)")
    common_write_args(rgn)
    rgn.set_defaults(func=_cli_regen)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
