E=(release/tools/append-pipeline-event.sh --version work-nature-and-axis-model --stage 7)
R='ref:https://github.com/cody-hutson/pmo-platform/issues/7973'
S7='ref:https://github.com/cody-hutson/pmo-platform/issues/7973#issuecomment-5862203943'
"${E[@]}" --event-type test-run --event-subtype suite-skip --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome resolved --payload "ms:#426; suite:NONE; selected-by:no-match; map-row:6; reason:doc-only-change; sha:05a8e6a0"
"${E[@]}" --event-type gate-outcome --event-subtype dt-pass --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome resolved --payload "ms:#426; projects_to:calibration-data.md; verdict:PASS; blockers:0; major:2; minor:6; cosmetic:1; tier-1:7; tier-2:1; escapes:S6=8; pass:1; sha:05a8e6a0; $S7"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-01; sev:Major; origin:S6; B5 read order names #7972 where B5 names #7971; fix:plan D5 row + V15 + Stage-8 brief; sha:05a8e6a0; $R"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-02; sev:Major; origin:S6; AC-3 probe is whole-file and passes the B4 mutant; fix:section-scoped probe; sha:05a8e6a0; $R"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-03; sev:Minor; origin:S6; Verification Evidence records executor exit 0, observed exit 3; sha:05a8e6a0; $R"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-04; sev:Minor; origin:S6; B4 limb 3: no ADR-schema run and 7 rows without a mutant arm in Verification Evidence; sha:05a8e6a0; $R"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-05; sev:Minor; origin:S6; V-15 and V-21 authority quotes are head text, not pre-filing text; codes stand; sha:05a8e6a0; $R"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-06; sev:Minor; origin:S6; pool-level concept-1 counts rest on an unpublished pass-1c list with no probe record; sha:05a8e6a0; $R"
"${E[@]}" --event-type scope-change --event-subtype tier-1-adjust --actor 'spoke:#7973' --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; finding:F-07; sev:Minor; origin:S6; plan non-scope row names a path that does not exist (pipeline/ for standards/); sha:05a8e6a0; $R"
"${E[@]}" --event-type decision --event-subtype empirical-verification-finding --actor hub --subject 'sub-task:#7973' --reversibility CHEAP --outcome resolved --payload "ms:#426; s7-verified@05a8e6a0: F-01 F-02 F-03 F-05 F-07 reproduced, F-04 claim line confirmed; return value carried prose outside the 4-line schema (minor); hub:concur-PASS; $R"
"${E[@]}" --event-type decision --event-subtype d-class --actor hub --subject 'sub-task:#7973' --reversibility CHEAP --outcome resolved --payload "ms:#426; d:S7-dispositions; F-01..F-07 fix-now (Tier 1, framework Step 1: cheap, open branch); F-08 accept (Note); F-09 carry to Stage 9 readiness scan; $R"
"${E[@]}" --event-type iteration --event-subtype dt-eng-pass-0 --actor hub --subject 'issue:#7959' --reversibility CHEAP --outcome pending --payload "ms:#426; projects_to:iteration-log.md; boundary:Stage 7 to Stage 6; trigger:Tier 1; findings:F-01..F-07; route:resume Stage-6 spoke for fix(dt) pass; $R"
"${E[@]}" --event-type decision --event-subtype action-item-opened --actor hub --subject 'sub-task:#7973' --reversibility CHEAP --outcome resolved --payload "ms:#426; AI-009; category:decision-deferred; owner:hub; carry two follow-up-card questions (executor dispatch gap; domain_practice placement drift) to the Stage-9 briefing; $R"
